### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by fanatid**
Now hash function and count not hard-coded (i.e. JS version is compatible with OpenSSL version)

ping @calvinmetcalf

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
so we do actually use this internally several places so if you were to switch the parameter order to put the new ones at the end and default to the previous hard coded things that would make things much easier

**Comment by fanatid** [comment]
Yea, I know that this package is used in a few packages, but I wanted same arguments order as in OpenSSL and also I wanted remove dependencies.. so I would like to see major version bump.
But if you insist I can make createHash and count optional arguments.

**Comment by calvinmetcalf** [comment]
is this needed for something ?

**Comment by fanatid** [comment]
> is this needed for something ?

Probably not.

----

I made `createHash` and `count` optional parameters.

**Comment by dcousens** [comment]
@fanatid can this be merged before https://github.com/crypto-browserify/EVP_BytesToKey/pull/6 ?

**Comment by fanatid** [comment]
I think it can, but only if you change arguments order to old style.. unfortunately this will be not compliant with openssl version.

**Comment by dcousens** [comment]
@fanatid can't we just shim it?

**Comment by fanatid** [comment]
maybe, what's wrong with major bump?

**Comment by dcousens** [comment]
Nothing,  you're right.  I'll do the fixes in the other modules.

**Pull request merged**
